[package]
name = "httplatency"
version = "0.1.0"
authors = ["Cameron <code@cameronford.net>"]

[[bin]]
doc = false
name = "httplatency"
path = "src/bin/main.rs"

[dependencies]
hyper = "0.7"
rustc-serialize = "0.3"
log = "0.3"
getopts = "0.2"
time = "0.1"
url = "0.5"
